project:
  type: website

website:
  title: "modelo_poisson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-line-numbers: true
    toc-title: "Contenido"
    toc-location: right
    df-print: paged

execute: 
  cache: true



