project:
  type: website

website:
  title: "Modelo de Clasificación"
  navbar:
    left:
      - href: modelp.qmd
        text: modelo poisson
      - href: modelc.qmd
        text: Ajuste del modelo

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-line-numbers: true
    toc-title: "Contenido"
    toc-location: right
    df-print: paged

execute: 
  cache: true



